# web-server:
#   image: httpd
#   container_name: "web-server"
#   ports:
#     - "8003:80"

version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql:cached

  web:
    image: docker_app
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install --path vendor/bundle && bin/rails db:create && bin/rails webpacker:install && bin/rails s -p 3000 -b '0.0.0.0'"
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle:cached

    depends_on:
      - db
    entrypoint: ./entrypoint.sh

volumes:
  bundle:
    driver: local
  mysql:
    driver: local
